# 可选实验：Python、NumPy与向量化
本课程中使用的科学计算简介，特别是NumPy科学计算包及其在Python中的应用。

# 目录
- [&nbsp;&nbsp;1.1 目标](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 参考资料](#toc_40015_1.2)
- [2 Python和NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 向量](#toc_40015_3)
- [&nbsp;&nbsp;3.1 概述](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy数组](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 向量创建](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 向量运算](#toc_40015_3.4)
- [4 矩阵](#toc_40015_4)
- [&nbsp;&nbsp;4.1 概述](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy数组](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 矩阵创建](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 矩阵运算](#toc_40015_4.4)


In [2]:
import numpy as np    # 使用np作为numpy的别名是非官方标准
import time

<a name="toc_40015_1.1"></a>
## 1.1 目标
在本实验中，你将：
- 回顾课程1中使用的NumPy和Python特性

<a name="toc_40015_1.2"></a>
## 1.2 参考资料
- NumPy文档，包括基本介绍：[NumPy.org](https://NumPy.org/doc/stable/)
- 一个有挑战性的主题：[NumPy广播](https://NumPy.org/doc/stable/user/basics.broadcasting.html)


<a name="toc_40015_2"></a>
# 2 Python和NumPy <a name='Python and NumPy'></a>
Python是本课程使用的编程语言。它有一组数值数据类型和算术运算。NumPy是一个库，它扩展了Python的基础功能，添加了更丰富的数据集，包括更多数值类型、向量、矩阵和许多矩阵函数。NumPy和Python配合得相当无缝。Python算术运算符可以用于NumPy数据类型，许多NumPy函数也接受Python数据类型。


<a name="toc_40015_3"></a>
# 3 向量
<a name="toc_40015_3.1"></a>
## 3.1 概述
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >在本课程中，向量是有序的数字数组。在符号表示中，向量用小写粗体字母表示，如$\mathbf{x}$。向量的所有元素都是相同类型。例如，向量不能同时包含字符和数字。数组中的元素数量通常称为*维度*，尽管数学家可能更喜欢*秩*。所示向量的维度为$n$。向量的元素可以通过索引引用。在数学环境中，索引通常从1到n。在计算机科学和这些实验中，索引通常从0到n-1。在符号表示中，向量的元素在单独引用时会用下标表示索引，例如，向量$\mathbf{x}$的第$0$个元素是$x_0$。注意，在这种情况下x不是粗体。


<a name="toc_40015_3.2"></a>
## 3.2 NumPy数组

NumPy的基本数据结构是可索引的n维*数组*，包含相同类型（`dtype`）的元素。你可能注意到我们已经重载了'维度'这个术语。上面它指的是向量中元素的数量，这里维度指的是数组的索引数量。一维或1-D数组有一个索引。在课程1中，我们将向量表示为NumPy 1-D数组。

 - 1-D数组，形状(n,)：n个元素，索引从[0]到[n-1]
 

<a name="toc_40015_3.3"></a>
## 3.3 向量创建


NumPy中的数据创建例程通常有一个参数是对象的形状。对于1-D结果，这可以是单个值，也可以是元组(n,m,...)指定结果的形状。下面是使用这些例程创建向量的示例。

In [3]:
# NumPy例程，分配内存并用值填充数组
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.30433563 0.82215562 0.14511873 0.59745871], a shape = (4,), a data type = float64


一些数据创建例程不接受形状元组：

In [4]:
# NumPy例程，分配内存并用值填充数组，但不接受形状作为输入参数
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.1389697  0.8780921  0.18132867 0.92494173], a shape = (4,), a data type = float64


也可以手动指定值。

In [5]:
# NumPy例程，分配内存并用用户指定的值填充
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


这些都创建了一个包含四个元素的一维向量`a`。`a.shape`返回维度。这里我们看到a.shape = `(4,)`表示一个包含4个元素的1-D数组。

<a name="toc_40015_3.4"></a>
## 3.4 向量运算
让我们探索一些使用向量的运算。
<a name="toc_40015_3.4.1"></a>
### 3.4.1 索引
向量的元素可以通过索引和切片来访问。NumPy提供了非常完整的索引和切片功能。我们这里只探索课程所需的基础知识。参考[切片和索引](https://NumPy.org/doc/stable/reference/arrays.indexing.html)了解更多细节。
**索引**是指通过元素在数组中的位置来引用*一个元素*。
**切片**是指根据索引从数组中获取*子集*元素。
NumPy从零开始索引，因此向量$\mathbf{a}$的第3个元素是`a[2]`。

In [6]:
# 1-D向量的向量索引操作
a = np.arange(10)
print(a)

# 访问一个元素
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, 访问一个元素返回标量")

# 访问最后一个元素，负索引从末尾开始计数
print(f"a[-1] = {a[-1]}")

# 索引必须在向量范围内，否则会产生错误
try:
    c = a[10]
except Exception as e:
    print("你将看到的错误信息是：")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 切片
切片使用三个值（`start:stop:step`）创建索引数组。值的子集也是有效的。其用法最好通过示例来说明：

In [7]:
# 向量切片操作
a = np.arange(10)
print(f"a         = {a}")

# 访问5个连续元素 (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# 访问间隔两个元素的3个元素
c = a[2:7:2];     print("a[2:7:2] = ", c)

# 访问索引3及以上的所有元素
c = a[3:];        print("a[3:]    = ", c)

# 访问索引3以下的所有元素
c = a[:3];        print("a[:3]    = ", c)

# 访问所有元素
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 单向量运算
有许多有用的运算涉及对单个向量的操作。

In [8]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# 对a的元素取反
b = -a 
print(f"b = -a        : {b}")

# 对a的所有元素求和，返回标量
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 向量-向量逐元素运算
大多数NumPy算术、逻辑和比较运算也适用于向量。这些运算符是逐元素工作的。例如
$$ c_i = a_i + b_i $$

In [9]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


当然，为了使这正常工作，向量必须是**相同大小**的：

In [10]:
# 尝试不匹配的向量运算
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("你将看到的错误信息是：")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 标量-向量运算
向量可以被标量值'缩放'。标量值就是一个数字。标量乘以向量的所有元素。

In [11]:
a = np.array([1, 2, 3, 4])

# 用标量乘以a
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 向量-向量点积
点积是线性代数和NumPy的主要内容。这是本课程中广泛使用的运算，应该很好地理解。点积如下所示。

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800> 

点积对两个向量的值进行逐元素相乘，然后对结果求和。
向量点积要求两个向量的维度相同。

让我们在下面实现我们自己的点积版本：

**使用for循环**，实现一个函数，返回两个向量的点积。函数返回给定输入$a$和$b$：
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
假设`a`和`b`具有相同的形状。

In [13]:
def my_dot(a, b): 
    """
   计算两个向量的点积
 
    参数:
      a (ndarray (n,)):  输入向量 
      b (ndarray (n,)):  与a维度相同的输入向量
    
    返回:
      x (标量): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [14]:
# 测试1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


注意，点积预期返回标量值。

让我们尝试使用`np.dot`进行相同的操作。

In [15]:
# 测试1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


上面，你会注意到1-D的结果与我们的实现匹配。

<a name="toc_40015_3.4.7"></a>
### 3.4.7 速度需求：向量 vs for循环
我们使用NumPy库是因为它提高了速度和内存效率。让我们演示一下：

In [16]:
np.random.seed(1)
a = np.random.rand(10000000)  # 非常大的数组
b = np.random.rand(10000000)

tic = time.time()  # 捕获开始时间
c = np.dot(a, b)
toc = time.time()  # 捕获结束时间

print(f"np.dot(a, b) =  {c:.4f}")
print(f"向量化版本持续时间: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # 捕获开始时间
c = my_dot(a,b)
toc = time.time()  # 捕获结束时间

print(f"my_dot(a, b) =  {c:.4f}")
print(f"循环版本持续时间: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  # 从内存中删除这些大数组

np.dot(a, b) =  2501072.5817
Vectorized version duration: 166.1341 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 9434.8249 ms 


因此，在这个例子中，向量化提供了很大的加速。这是因为NumPy更好地利用了底层硬件中可用的数据并行性。GPU和现代CPU实现了单指令多数据（SIMD）管道，允许多个操作并行执行。这在机器学习中至关重要，因为数据集通常非常大。

<a name="toc_12345_3.4.8"></a>
### 3.4.8 课程1中的向量-向量运算
向量-向量运算将在课程1中频繁出现。原因如下：
- 展望未来，我们的示例将存储在维度为(m,n)的数组`X_train`中。这将在上下文中进一步解释，但这里重要的是要注意它是一个二维数组或矩阵（参见下一节关于矩阵的内容）。
- `w`将是一个形状为(n,)的一维向量。
- 我们将通过循环遍历示例来执行操作，通过索引X提取每个示例单独处理。例如：`X[i]`
- `X[i]`返回形状为(n,)的值，一个一维向量。因此，涉及`X[i]`的操作通常是向量-向量运算。

这是一个有点冗长的解释，但在执行向量操作时，对齐和理解操作数的形状很重要。

In [18]:
# 显示课程1的常见示例
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 矩阵


<a name="toc_40015_4.1"></a>
## 4.1 概述
矩阵是二维数组。矩阵的所有元素都是相同类型。在符号表示中，矩阵用大写粗体字母表示，如$\mathbf{X}$。在这个和其他实验中，`m`通常是行数，`n`是列数。矩阵的元素可以用二维索引引用。在数学环境中，索引中的数字通常从1到n。在计算机科学和这些实验中，索引将从0到n-1。
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> 通用矩阵符号，第一个索引是行，第二个是列 </figcaption>
<figure/>

<a name="toc_40015_4.2"></a>
## 4.2 NumPy数组

NumPy的基本数据结构是可索引的n维*数组*，包含相同类型（`dtype`）的元素。这些在前面已经描述过。矩阵有二维索引[m,n]。

在课程1中，2-D矩阵用于保存训练数据。训练数据是$m$个示例乘以$n$个特征，创建一个(m,n)数组。课程1不直接对矩阵进行操作，而是通常将示例提取为向量并对其进行操作。下面你将回顾：
- 数据创建
- 切片和索引

<a name="toc_40015_4.3"></a>
## 4.3 矩阵创建
创建1-D向量的相同函数将创建2-D或n-D数组。这里有一些示例


下面，提供形状元组以获得2-D结果。注意NumPy如何使用括号表示每个维度。进一步注意，NumPy在打印时每行打印一行。


In [21]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


也可以手动指定数据。维度用额外的括号指定，匹配上面打印的格式。

In [19]:
# NumPy例程，分配内存并用用户指定的值填充
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # 也可以
              [4],   # 将值分开
              [3]]); # 分成单独的行
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 矩阵运算
让我们探索一些使用矩阵的运算。

<a name="toc_40015_4.4.1"></a>
### 4.4.1 索引


矩阵包含第二个索引。两个索引描述[行,列]。访问可以返回元素或行/列。见下文：

In [22]:
# 矩阵上的向量索引操作
a = np.arange(6).reshape(-1, 2)   # reshape是创建矩阵的便捷方法
print(f"a.shape: {a.shape}, \na= {a}")

# 访问一个元素
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} 访问一个元素返回标量\n")

# 访问一行
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


值得注意的是最后一个示例。仅指定行访问矩阵将返回一个*1-D向量*。

**重塑**  
前面的示例使用[reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)来塑造数组。  
`a = np.arange(6).reshape(-1, 2) `   
这行代码首先创建了一个包含六个元素的*1-D向量*。然后使用reshape命令将该向量重塑为*2-D*数组。这可以写成：  
`a = np.arange(6).reshape(3, 2) `  
以得到相同的3行2列数组。
-1参数告诉例程根据数组的大小和列数计算行数。


<a name="toc_40015_4.4.2"></a>
### 4.4.2 切片
切片使用三个值（`start:stop:step`）创建索引数组。值的子集也是有效的。其用法最好通过示例来说明：

In [23]:
# 2-D向量切片操作
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

# 访问5个连续元素 (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

# 在两行中访问5个连续元素 (start:stop:step)
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# 访问所有元素
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# 访问一行中的所有元素（非常常见的用法）
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# 相同于
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## 恭喜！
在本实验中，你掌握了课程1所需的Python和NumPy特性。